Version: 2
Name: PROMETHEUS
Sequence:
  - Order: 1
    Task: Flow.Parallel
    Children:
      - Task: Run.PrometheusToInflux
        Config:
          ExecutionId: "@{ExecutionId}"
          Url: "192.168.xxx.xxx"
          Port: "9090"
          QueriesRange:
            - "query_range_1"
            - "query_range_2"
          QueriesCustom:
            - "custom_query_1"
            - "custom_query_2"
          Measurement: PROMETHEUS
          Step: "1s"
          Stop: "stop_prometheus"
          Account: False
          Encryption: False 
      - Task: Flow.Sequence
        Children:
        - Task: Run.Delay
          Config:
            Time: 60
        - Task: Run.StopTask
          Config:
            ExecutionId: "@{ExecutionId}"
            Name: "stop_prometheus"
Standard: True
Dashboard:
  - Name: "query_range_1"
    Measurement: "PROMETHEUS"
    Field: "query_range_1"
    Type: Graph
    Interval: 1s
    Unit: bytes
    Size: [9, 12]
    Position: [8, 0]
    Lines: True
    Percentage: False